tfvars-path:
  - terraform/terraform.tfvars

exclude:
  - aws-ec2-no-public-egress-sgr
  - aws-s3-encryption-customer-key
  - aws-ec2-no-public-ip-subnet
  - aws-s3-enable-bucket-logging
  - aws-ec2-require-vpc-flow-logs-for-all-vpcs
